Saxon\Transform.exe -t	DeviceDesciptions/at90usb1287.xml	XSL/IO.xsl	> ../AVRCppLib/at90usb1287/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega128.xml		XSL/IO.xsl	> ../AVRCppLib/atmega128/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega164p.xml	XSL/IO.xsl	> ../AVRCppLib/atmega164p/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega168.xml		XSL/IO.xsl	> ../AVRCppLib/atmega168/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega324p.xml	XSL/IO.xsl	> ../AVRCppLib/atmega324p/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega48.xml		XSL/IO.xsl	> ../AVRCppLib/atmega48/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega64.xml		XSL/IO.xsl	> ../AVRCppLib/atmega64/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega644.xml		XSL/IO.xsl	> ../AVRCppLib/atmega644/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega644p.xml	XSL/IO.xsl	> ../AVRCppLib/atmega644p/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega8.xml		XSL/IO.xsl	> ../AVRCppLib/atmega8/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega8515.xml	XSL/IO.xsl	> ../AVRCppLib/atmega8515/IO.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega88.xml		XSL/IO.xsl	> ../AVRCppLib/atmega88/IO.h
