Saxon\Transform.exe -t	DeviceDesciptions/at90usb1287.xml	XSL/SPI.xsl	> ../AVRCppLib/at90usb1287/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega128.xml		XSL/SPI.xsl	> ../AVRCppLib/atmega128/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega164p.xml	XSL/SPI.xsl	> ../AVRCppLib/atmega164p/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega168.xml		XSL/SPI.xsl	> ../AVRCppLib/atmega168/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega324p.xml	XSL/SPI.xsl	> ../AVRCppLib/atmega324p/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega48.xml		XSL/SPI.xsl	> ../AVRCppLib/atmega48/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega64.xml		XSL/SPI.xsl	> ../AVRCppLib/atmega64/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega644.xml		XSL/SPI.xsl	> ../AVRCppLib/atmega644/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega644p.xml	XSL/SPI.xsl	> ../AVRCppLib/atmega644p/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega8.xml		XSL/SPI.xsl	> ../AVRCppLib/atmega8/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega8515.xml	XSL/SPI.xsl	> ../AVRCppLib/atmega8515/SPI.h
Saxon\Transform.exe -t	DeviceDesciptions/atmega88.xml		XSL/SPI.xsl	> ../AVRCppLib/atmega88/SPI.h
