Saxon\Transform.exe -t	Registers_XML/at90usb1287.xml	xSL/IO.xsl	> ../AVRCppLib/at90usb1287/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega128.xml	xSL/IO.xsl	> ../AVRCppLib/atmega128/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega164p.xml	xSL/IO.xsl	> ../AVRCppLib/atmega164p/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega168.xml	xSL/IO.xsl	> ../AVRCppLib/atmega168/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega324p.xml	xSL/IO.xsl	> ../AVRCppLib/atmega324p/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega48.xml	xSL/IO.xsl	> ../AVRCppLib/atmega48/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega64.xml	xSL/IO.xsl	> ../AVRCppLib/atmega64/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega644.xml	xSL/IO.xsl	> ../AVRCppLib/atmega644/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega8.xml	xSL/IO.xsl	> ../AVRCppLib/atmega8/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega8515.xml	xSL/IO.xsl	> ../AVRCppLib/atmega8515/IO.h
Saxon\Transform.exe -t	Registers_XML/atmega88.xml	xSL/IO.xsl	> ../AVRCppLib/atmega88/IO.h